* Trip Types
  I think I'm pretty set on doing a Unit loop. Would like to see some glaciers!
* Terrain Types
** River Crossings
   There are no bridges accross rivers. Water temperature is cold (36F) so a
   cold immersion could potentially cause hypothermia.
   Advice:
   1. Keep hiking boots on to protect your feet.
   2. Use a trekking pole (or a stick) to gauge water depth.
*** Gravel River Bars
    Flat, rocky surfaces that characterize most major rivers in the park.
** Glacier Crossings
   These present numeous hazards. Can't cross the upper ice/snow portions of a
   glacier without appropriate equipment. Crossing 'lower glacial moraine'
   possible but requires caution.
** Boreal Forest (Taiga)
   Appears at lower elevations (less than 3k feet above sea level). Not great
   terrain for camping due to lack of visibility.
** Bushy Tundra
   Some backcountry units require bushwacking through dense brush that may
   exceed 6 feed in height. Bad for camping due to extremely limited visibility.
   Surprise encounters with wildlife possible.
** Alpine Tundra
   Exists at higher elevations (above 3k feet). Affords good visibility. Camping
   can be difficult due to angles/slopes of hills.
** Glacier Moraines
   Denoted on maps by stippled areas. Consists of ice covered with dirt and
   debris. Makes for very rough travel with many hazards.
* Potential Units
  Some quick summaries of some interesting-sounding units that don't require
  expert backpacking skills.
** Beginner Units
*** Unit 1 - Triple Lakes
    One of the few areas in the park with a trail. Good option for large groups.
*** Unit 9 - East Branch Toklat River
    Wide-open gravel bar, surrounded by high, rugged peaks. Known for classic
    mountain scenery and quick access to large expanses of alpine tundra. Very
    popular so it is diffucult to get a permit.
*** Unit 10 - West Branch Upper Toklat River
    Similar to unit 9, but on a slightly larger scale.
*** Unit 11 - Stony Dome
    Easy to get away from the road. Smallest backcountry unit in the park so
    suited for an overnight trip or a hike in connection with another unit.
*** Unit 12 - Sunrise and Sunset Glaciers
    Surrounded by tundra benches and high peaks. Very popular unit so expect
    to have difficult getting a permit. Don't expect as much solitude.
*** Unit 13 - Mount Eielson
* TODO Gear
1. [ ] waterproof hiking boots
2. [ ] 2P wool or synthetic socks
3. [ ] Trekking pole
4. [ ] Rain jacket/rain pants
5. [ ] polypropylene, nylon, fleece or wool clothing
6. [ ] stove, fuel, cookware, water bottles
7. [ ] water filter
8. [ ] Dense, high calorie-food
9. [ ] Compass and map
10. [ ] Toilet paper, trowel, bag
11. [ ] Tent with rain fly and waterproof floor
    - REI quarter dome
12. [ ] Sleeping bag/pad
13. [ ] Insect repellent/head net
14. [ ] Emergency gear - first aid kit, knife, signaling device
15. [ ] Bear spray
16. [ ] Backpack rain cover
17. [ ] Change of shoes
18. [ ] Camera with waterproof case
19. [ ] Toiletries
20. [ ] Sunscreen, sunglasses, hat
* Food
