* Trip Types
  I think I'm pretty set on doing a Unit loop. Would like to see some glaciers!
* Terrian Types
** River Crossings
   There are no bridges accross rivers. Water temperature is cold (36F) so a
   cold immersion could potentially cause hypothermia.
   Advice:
   1. Keep hiking boots on to protect your feet.
   2. Use a trekking pole (or a stick) to gauge water depth.
* Potential Units
  Some quick summaries of some interesting-sounding units that don't require
  expert backpacking skills.
** Beginner Units
*** Unit 1 - Triple Lakes
    One of the few areas in the park with a trail. Good option for large groups.
*** Unit 9 - East Branch Toklat River
    Wide-open gravel bar, surrounded by high, rugged peaks. Known for classic
    mountain scenery and quick access to large expanses of alpine tundra. Very
    popular so it is diffucult to get a permit.
*** Unit 10 - West Branch Upper Toklat River
    Similar to unit 9, but on a slightly larger scale.
*** Unit 11 - Stony Dome
    Easy to get away from the road. Smallest backcountry unit in the park so
    suited for an overnight trip or a hike in connection with another unit.
*** Unit 12 - Sunrise and Sunset Glaciers
    Surrounded by tundra benches and high peaks. Very popular unit so expect
    to have difficult getting a permit. Don't expect as much solitude.
*** Unit 13 - Mount Eielson
* TODO Gear
1. [ ] waterproof hiking boots
2. [ ] 2P wool or synthetic socks
3. [ ] Trekking pole
4. [ ] Rain jacket/rain pants
5. [ ] polypropylene, nylon, fleece or wool clothing
6. [ ] stove, fuel, cookware, water bottles
7. [ ] water filter
8. [ ] Dense, high calorie-food
9. [ ] Compass and map
10. [ ] Toilet paper, trowel, bag
11. [ ] Tent with rain fly and waterproof floor
12. [ ] Sleeping bag/pad
13. [ ] Insect repellent/head net
14. [ ] Insect repellent/head net
15. [ ] Emergency gear - first aid kit, knife, signaling device
16. [ ] Bear spray
17. [ ] Backpack rain cover
18. [ ] Change of shoes
19. [ ] Camera with waterproof case
20. [ ] Toiletries
21. [ ] Sunscreen, sunglasses, hat
* Food
